version: '3'
services:
  db:
    image: mysql
    environment:
          MYSQL_ROOT_PASSWORD: mysqlRootPassword
          MYSQL_DATABASE: myapp_development
          MYSQL_USER: rails
          MYSQL_PASSWORD: rails
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db
